apiVersion: v1
kind: Pod
metadata:
  name: oci-cloud-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  containers:
    - name: oci-cloud-controller-manager
      image: wcr.io/oracle/oci-cloud-controller-manager:0.1.2
      args:
        - --cloud-config=/etc/oci/cloud-provider.yaml
        - --cloud-provider=oci
        - --cluster-cidr=10.244.0.0/16
        - -v=2
      volumeMounts:
        - name: cfg
          mountPath: /etc/oci
          readOnly: true
        - name: kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
  volumes:
    - name: cfg
      secret:
        secretName: oci-cloud-controller-manager
    - name: kubernetes
      hostPath:
        path: /etc/kubernetes
